version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - sam build 
  post_build:
    commands:
      - sam deploy --stack-name sam_template.yml
# artifacts:
#   files:
#     - packaged-template.yml
