version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      # Install the AWS CLI and SAM CLI
      - pip3 install awscli aws-sam-cli
      
  build:
    commands:
      - sam validate --template template.yaml
      - sam build -t template.yaml
  post_build:
    commands:
    
      - echo Build started on `date`
      - echo Entered the build phase ...
      
      - sam build
      - sam deploy --no-confirm-changeset --no-fail-on-empty-changeset

      # Package SAM template
      - sam package --template-file sam_template.yml --s3-bucket samcli-python-bucket --output-template-file packaged.yaml
      # Deploy packaged SAM template
      - sam deploy --template-file packaged.yaml --stack-name samcli-python-stack --capabilities CAPABILITY_IAM
