version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Entered the build phase ...

      # Package SAM template
      - sam package --template-file sam_template.yml --s3-bucket samcli-python-bucket --output-template-file packaged.yaml
      # Deploy packaged SAM template
      - sam deploy --template-file packaged.yaml --stack-name samcli-python-stack --capabilities CAPABILITY_IAM
