AWSTemplateFormatVersion: '2010-09-09'
#testcase
Parameters:
  Region:
    Type: String
    Default: us-east-1
    Description: The AWS region in which to create resources.

  AccountId:
    Type: String
    Default: 548616401217
    Description: The AWS account ID where the resources will be created.
      
  Env:
    Type: String
    Default: dev
    Description: Environment name.
    

Resources:
  MyLambdaFunction1:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: !Sub '${Env}-user-api-1'
      Handler: lambda_functions/function1.lambda_handler
      Role: !GetAtt MyLambdaRole.Arn
      Runtime: python3.9
      Environment:
        Variables:
          env: !Sub '${Env}'
         
  MyLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: MyLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'


  MyRestApi1:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: !Sub '${Env}-user-api-1'
      EndpointConfiguration:
        Types:
          - REGIONAL


  MyResource1:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref MyRestApi1
      ParentId: !GetAtt MyRestApi1.RootResourceId
      PathPart: 'user'
 

  MyMethod1:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      RestApiId: !Ref MyRestApi1
      ResourceId: !Ref MyResource1
      HttpMethod:
        - POST
        - GET
        - DELETE
        - PATCH
        - POST
      AuthorizationType: NONE #COGNITO_USER_POOLS  # Set authorization type to COGNITO_USER_POOLS
     # AuthorizerId: !Ref MyAuthorizer  # Set the ID of the authorizer
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub 'arn:aws:apigateway:${Region}:lambda:path/2015-03-31/functions/${MyLambdaFunction1.Arn}/invocations'
        
        

  MyAuthorizer:
    Type: 'AWS::ApiGateway::Authorizer'
    Properties:
      Name: my-cognito-authorizer
      Type: COGNITO_USER_POOLS
      IdentitySource: method.request.header.Authorization
      RestApiId: !Ref MyRestApi1
      ProviderARNs:
        - !Sub arn:aws:cognito-idp:${Region}:${AccountId}:userpool/us-east-1_zHG6ezXPp    #${UserPoolId}

  MyDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn:
      - MyMethod1
      
    Properties:
      RestApiId: !Ref MyRestApi1

  MyStage:
    Type: 'AWS::ApiGateway::Stage'
    Properties:
      RestApiId: !Ref MyRestApi1
      DeploymentId: !Ref MyDeployment
      StageName: !Sub '${Env}'
      Variables:
        env: !Sub '${Env}'
        
  MyLambdaPermission1:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref MyLambdaFunction1
      Principal: apigateway.amazonaws.com
      SourceArn: 
        - !Sub 'arn:aws:execute-api:${Region}:${AccountId}:${MyRestApi1}/${Env}/GET/user'
        - !Sub 'arn:aws:execute-api:${Region}:${AccountId}:${MyRestApi1}/${Env}/DELETE/user'
        - !Sub 'arn:aws:execute-api:${Region}:${AccountId}:${MyRestApi1}/${Env}/PATCH/user'
        - !Sub 'arn:aws:execute-api:${Region}:${AccountId}:${MyRestApi1}/${Env}/POST/user'
        
      
            
 
