AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLambdaFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName : my-first-lambda-funtion
  
      Handler: lambda_function.lambda_handler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/lambda-execution-role'
      Runtime: python3.8
  MyApiGateway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: my-first-restapi
  MyApiResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId: !GetAtt [ MyApiGateway, RootResourceId ]
      PathPart: my-resource
      RestApiId: !Ref MyApiGateway
  MyApiMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      HttpMethod: GET
      ResourceId: !Ref MyApiResource
      RestApiId: !Ref MyApiGateway
      AuthorizationType: NONE
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub 'arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:548616401217:function:my-first-lambda-funtion/invocations'
  MyApiDeployment:
    Type: 'AWS::ApiGateway::Deployment'
    DependsOn: MyApiMethod
    Properties:
      RestApiId: !Ref MyApiGateway
      StageName: prod
  MyLambdaPermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref MyLambdaFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub 'arn:aws:execute-api:us-east-1:548616401217:my-first-restapi/*/GET/my-resource'
